// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/aws-sdk-go-v2/service/cloudwatchlogs/cloudwatchlogsiface (interfaces: ClientAPI)

// Package mock_cloudwatchlogsiface is a generated GoMock package.
package mock_cloudwatchlogsiface

import (
	cloudwatchlogs "github.com/aws/aws-sdk-go-v2/service/cloudwatchlogs"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockClientAPI is a mock of ClientAPI interface
type MockClientAPI struct {
	ctrl     *gomock.Controller
	recorder *MockClientAPIMockRecorder
}

// MockClientAPIMockRecorder is the mock recorder for MockClientAPI
type MockClientAPIMockRecorder struct {
	mock *MockClientAPI
}

// NewMockClientAPI creates a new mock instance
func NewMockClientAPI(ctrl *gomock.Controller) *MockClientAPI {
	mock := &MockClientAPI{ctrl: ctrl}
	mock.recorder = &MockClientAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockClientAPI) EXPECT() *MockClientAPIMockRecorder {
	return m.recorder
}

// AssociateKmsKeyRequest mocks base method
func (m *MockClientAPI) AssociateKmsKeyRequest(arg0 *cloudwatchlogs.AssociateKmsKeyInput) cloudwatchlogs.AssociateKmsKeyRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssociateKmsKeyRequest", arg0)
	ret0, _ := ret[0].(cloudwatchlogs.AssociateKmsKeyRequest)
	return ret0
}

// AssociateKmsKeyRequest indicates an expected call of AssociateKmsKeyRequest
func (mr *MockClientAPIMockRecorder) AssociateKmsKeyRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssociateKmsKeyRequest", reflect.TypeOf((*MockClientAPI)(nil).AssociateKmsKeyRequest), arg0)
}

// CancelExportTaskRequest mocks base method
func (m *MockClientAPI) CancelExportTaskRequest(arg0 *cloudwatchlogs.CancelExportTaskInput) cloudwatchlogs.CancelExportTaskRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelExportTaskRequest", arg0)
	ret0, _ := ret[0].(cloudwatchlogs.CancelExportTaskRequest)
	return ret0
}

// CancelExportTaskRequest indicates an expected call of CancelExportTaskRequest
func (mr *MockClientAPIMockRecorder) CancelExportTaskRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelExportTaskRequest", reflect.TypeOf((*MockClientAPI)(nil).CancelExportTaskRequest), arg0)
}

// CreateExportTaskRequest mocks base method
func (m *MockClientAPI) CreateExportTaskRequest(arg0 *cloudwatchlogs.CreateExportTaskInput) cloudwatchlogs.CreateExportTaskRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateExportTaskRequest", arg0)
	ret0, _ := ret[0].(cloudwatchlogs.CreateExportTaskRequest)
	return ret0
}

// CreateExportTaskRequest indicates an expected call of CreateExportTaskRequest
func (mr *MockClientAPIMockRecorder) CreateExportTaskRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateExportTaskRequest", reflect.TypeOf((*MockClientAPI)(nil).CreateExportTaskRequest), arg0)
}

// CreateLogGroupRequest mocks base method
func (m *MockClientAPI) CreateLogGroupRequest(arg0 *cloudwatchlogs.CreateLogGroupInput) cloudwatchlogs.CreateLogGroupRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLogGroupRequest", arg0)
	ret0, _ := ret[0].(cloudwatchlogs.CreateLogGroupRequest)
	return ret0
}

// CreateLogGroupRequest indicates an expected call of CreateLogGroupRequest
func (mr *MockClientAPIMockRecorder) CreateLogGroupRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLogGroupRequest", reflect.TypeOf((*MockClientAPI)(nil).CreateLogGroupRequest), arg0)
}

// CreateLogStreamRequest mocks base method
func (m *MockClientAPI) CreateLogStreamRequest(arg0 *cloudwatchlogs.CreateLogStreamInput) cloudwatchlogs.CreateLogStreamRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLogStreamRequest", arg0)
	ret0, _ := ret[0].(cloudwatchlogs.CreateLogStreamRequest)
	return ret0
}

// CreateLogStreamRequest indicates an expected call of CreateLogStreamRequest
func (mr *MockClientAPIMockRecorder) CreateLogStreamRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLogStreamRequest", reflect.TypeOf((*MockClientAPI)(nil).CreateLogStreamRequest), arg0)
}

// DeleteDestinationRequest mocks base method
func (m *MockClientAPI) DeleteDestinationRequest(arg0 *cloudwatchlogs.DeleteDestinationInput) cloudwatchlogs.DeleteDestinationRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDestinationRequest", arg0)
	ret0, _ := ret[0].(cloudwatchlogs.DeleteDestinationRequest)
	return ret0
}

// DeleteDestinationRequest indicates an expected call of DeleteDestinationRequest
func (mr *MockClientAPIMockRecorder) DeleteDestinationRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDestinationRequest", reflect.TypeOf((*MockClientAPI)(nil).DeleteDestinationRequest), arg0)
}

// DeleteLogGroupRequest mocks base method
func (m *MockClientAPI) DeleteLogGroupRequest(arg0 *cloudwatchlogs.DeleteLogGroupInput) cloudwatchlogs.DeleteLogGroupRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLogGroupRequest", arg0)
	ret0, _ := ret[0].(cloudwatchlogs.DeleteLogGroupRequest)
	return ret0
}

// DeleteLogGroupRequest indicates an expected call of DeleteLogGroupRequest
func (mr *MockClientAPIMockRecorder) DeleteLogGroupRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLogGroupRequest", reflect.TypeOf((*MockClientAPI)(nil).DeleteLogGroupRequest), arg0)
}

// DeleteLogStreamRequest mocks base method
func (m *MockClientAPI) DeleteLogStreamRequest(arg0 *cloudwatchlogs.DeleteLogStreamInput) cloudwatchlogs.DeleteLogStreamRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLogStreamRequest", arg0)
	ret0, _ := ret[0].(cloudwatchlogs.DeleteLogStreamRequest)
	return ret0
}

// DeleteLogStreamRequest indicates an expected call of DeleteLogStreamRequest
func (mr *MockClientAPIMockRecorder) DeleteLogStreamRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLogStreamRequest", reflect.TypeOf((*MockClientAPI)(nil).DeleteLogStreamRequest), arg0)
}

// DeleteMetricFilterRequest mocks base method
func (m *MockClientAPI) DeleteMetricFilterRequest(arg0 *cloudwatchlogs.DeleteMetricFilterInput) cloudwatchlogs.DeleteMetricFilterRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMetricFilterRequest", arg0)
	ret0, _ := ret[0].(cloudwatchlogs.DeleteMetricFilterRequest)
	return ret0
}

// DeleteMetricFilterRequest indicates an expected call of DeleteMetricFilterRequest
func (mr *MockClientAPIMockRecorder) DeleteMetricFilterRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMetricFilterRequest", reflect.TypeOf((*MockClientAPI)(nil).DeleteMetricFilterRequest), arg0)
}

// DeleteQueryDefinitionRequest mocks base method
func (m *MockClientAPI) DeleteQueryDefinitionRequest(arg0 *cloudwatchlogs.DeleteQueryDefinitionInput) cloudwatchlogs.DeleteQueryDefinitionRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteQueryDefinitionRequest", arg0)
	ret0, _ := ret[0].(cloudwatchlogs.DeleteQueryDefinitionRequest)
	return ret0
}

// DeleteQueryDefinitionRequest indicates an expected call of DeleteQueryDefinitionRequest
func (mr *MockClientAPIMockRecorder) DeleteQueryDefinitionRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteQueryDefinitionRequest", reflect.TypeOf((*MockClientAPI)(nil).DeleteQueryDefinitionRequest), arg0)
}

// DeleteResourcePolicyRequest mocks base method
func (m *MockClientAPI) DeleteResourcePolicyRequest(arg0 *cloudwatchlogs.DeleteResourcePolicyInput) cloudwatchlogs.DeleteResourcePolicyRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteResourcePolicyRequest", arg0)
	ret0, _ := ret[0].(cloudwatchlogs.DeleteResourcePolicyRequest)
	return ret0
}

// DeleteResourcePolicyRequest indicates an expected call of DeleteResourcePolicyRequest
func (mr *MockClientAPIMockRecorder) DeleteResourcePolicyRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteResourcePolicyRequest", reflect.TypeOf((*MockClientAPI)(nil).DeleteResourcePolicyRequest), arg0)
}

// DeleteRetentionPolicyRequest mocks base method
func (m *MockClientAPI) DeleteRetentionPolicyRequest(arg0 *cloudwatchlogs.DeleteRetentionPolicyInput) cloudwatchlogs.DeleteRetentionPolicyRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRetentionPolicyRequest", arg0)
	ret0, _ := ret[0].(cloudwatchlogs.DeleteRetentionPolicyRequest)
	return ret0
}

// DeleteRetentionPolicyRequest indicates an expected call of DeleteRetentionPolicyRequest
func (mr *MockClientAPIMockRecorder) DeleteRetentionPolicyRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRetentionPolicyRequest", reflect.TypeOf((*MockClientAPI)(nil).DeleteRetentionPolicyRequest), arg0)
}

// DeleteSubscriptionFilterRequest mocks base method
func (m *MockClientAPI) DeleteSubscriptionFilterRequest(arg0 *cloudwatchlogs.DeleteSubscriptionFilterInput) cloudwatchlogs.DeleteSubscriptionFilterRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSubscriptionFilterRequest", arg0)
	ret0, _ := ret[0].(cloudwatchlogs.DeleteSubscriptionFilterRequest)
	return ret0
}

// DeleteSubscriptionFilterRequest indicates an expected call of DeleteSubscriptionFilterRequest
func (mr *MockClientAPIMockRecorder) DeleteSubscriptionFilterRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSubscriptionFilterRequest", reflect.TypeOf((*MockClientAPI)(nil).DeleteSubscriptionFilterRequest), arg0)
}

// DescribeDestinationsRequest mocks base method
func (m *MockClientAPI) DescribeDestinationsRequest(arg0 *cloudwatchlogs.DescribeDestinationsInput) cloudwatchlogs.DescribeDestinationsRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeDestinationsRequest", arg0)
	ret0, _ := ret[0].(cloudwatchlogs.DescribeDestinationsRequest)
	return ret0
}

// DescribeDestinationsRequest indicates an expected call of DescribeDestinationsRequest
func (mr *MockClientAPIMockRecorder) DescribeDestinationsRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeDestinationsRequest", reflect.TypeOf((*MockClientAPI)(nil).DescribeDestinationsRequest), arg0)
}

// DescribeExportTasksRequest mocks base method
func (m *MockClientAPI) DescribeExportTasksRequest(arg0 *cloudwatchlogs.DescribeExportTasksInput) cloudwatchlogs.DescribeExportTasksRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeExportTasksRequest", arg0)
	ret0, _ := ret[0].(cloudwatchlogs.DescribeExportTasksRequest)
	return ret0
}

// DescribeExportTasksRequest indicates an expected call of DescribeExportTasksRequest
func (mr *MockClientAPIMockRecorder) DescribeExportTasksRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeExportTasksRequest", reflect.TypeOf((*MockClientAPI)(nil).DescribeExportTasksRequest), arg0)
}

// DescribeLogGroupsRequest mocks base method
func (m *MockClientAPI) DescribeLogGroupsRequest(arg0 *cloudwatchlogs.DescribeLogGroupsInput) cloudwatchlogs.DescribeLogGroupsRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeLogGroupsRequest", arg0)
	ret0, _ := ret[0].(cloudwatchlogs.DescribeLogGroupsRequest)
	return ret0
}

// DescribeLogGroupsRequest indicates an expected call of DescribeLogGroupsRequest
func (mr *MockClientAPIMockRecorder) DescribeLogGroupsRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeLogGroupsRequest", reflect.TypeOf((*MockClientAPI)(nil).DescribeLogGroupsRequest), arg0)
}

// DescribeLogStreamsRequest mocks base method
func (m *MockClientAPI) DescribeLogStreamsRequest(arg0 *cloudwatchlogs.DescribeLogStreamsInput) cloudwatchlogs.DescribeLogStreamsRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeLogStreamsRequest", arg0)
	ret0, _ := ret[0].(cloudwatchlogs.DescribeLogStreamsRequest)
	return ret0
}

// DescribeLogStreamsRequest indicates an expected call of DescribeLogStreamsRequest
func (mr *MockClientAPIMockRecorder) DescribeLogStreamsRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeLogStreamsRequest", reflect.TypeOf((*MockClientAPI)(nil).DescribeLogStreamsRequest), arg0)
}

// DescribeMetricFiltersRequest mocks base method
func (m *MockClientAPI) DescribeMetricFiltersRequest(arg0 *cloudwatchlogs.DescribeMetricFiltersInput) cloudwatchlogs.DescribeMetricFiltersRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeMetricFiltersRequest", arg0)
	ret0, _ := ret[0].(cloudwatchlogs.DescribeMetricFiltersRequest)
	return ret0
}

// DescribeMetricFiltersRequest indicates an expected call of DescribeMetricFiltersRequest
func (mr *MockClientAPIMockRecorder) DescribeMetricFiltersRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeMetricFiltersRequest", reflect.TypeOf((*MockClientAPI)(nil).DescribeMetricFiltersRequest), arg0)
}

// DescribeQueriesRequest mocks base method
func (m *MockClientAPI) DescribeQueriesRequest(arg0 *cloudwatchlogs.DescribeQueriesInput) cloudwatchlogs.DescribeQueriesRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeQueriesRequest", arg0)
	ret0, _ := ret[0].(cloudwatchlogs.DescribeQueriesRequest)
	return ret0
}

// DescribeQueriesRequest indicates an expected call of DescribeQueriesRequest
func (mr *MockClientAPIMockRecorder) DescribeQueriesRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeQueriesRequest", reflect.TypeOf((*MockClientAPI)(nil).DescribeQueriesRequest), arg0)
}

// DescribeQueryDefinitionsRequest mocks base method
func (m *MockClientAPI) DescribeQueryDefinitionsRequest(arg0 *cloudwatchlogs.DescribeQueryDefinitionsInput) cloudwatchlogs.DescribeQueryDefinitionsRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeQueryDefinitionsRequest", arg0)
	ret0, _ := ret[0].(cloudwatchlogs.DescribeQueryDefinitionsRequest)
	return ret0
}

// DescribeQueryDefinitionsRequest indicates an expected call of DescribeQueryDefinitionsRequest
func (mr *MockClientAPIMockRecorder) DescribeQueryDefinitionsRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeQueryDefinitionsRequest", reflect.TypeOf((*MockClientAPI)(nil).DescribeQueryDefinitionsRequest), arg0)
}

// DescribeResourcePoliciesRequest mocks base method
func (m *MockClientAPI) DescribeResourcePoliciesRequest(arg0 *cloudwatchlogs.DescribeResourcePoliciesInput) cloudwatchlogs.DescribeResourcePoliciesRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeResourcePoliciesRequest", arg0)
	ret0, _ := ret[0].(cloudwatchlogs.DescribeResourcePoliciesRequest)
	return ret0
}

// DescribeResourcePoliciesRequest indicates an expected call of DescribeResourcePoliciesRequest
func (mr *MockClientAPIMockRecorder) DescribeResourcePoliciesRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeResourcePoliciesRequest", reflect.TypeOf((*MockClientAPI)(nil).DescribeResourcePoliciesRequest), arg0)
}

// DescribeSubscriptionFiltersRequest mocks base method
func (m *MockClientAPI) DescribeSubscriptionFiltersRequest(arg0 *cloudwatchlogs.DescribeSubscriptionFiltersInput) cloudwatchlogs.DescribeSubscriptionFiltersRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeSubscriptionFiltersRequest", arg0)
	ret0, _ := ret[0].(cloudwatchlogs.DescribeSubscriptionFiltersRequest)
	return ret0
}

// DescribeSubscriptionFiltersRequest indicates an expected call of DescribeSubscriptionFiltersRequest
func (mr *MockClientAPIMockRecorder) DescribeSubscriptionFiltersRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeSubscriptionFiltersRequest", reflect.TypeOf((*MockClientAPI)(nil).DescribeSubscriptionFiltersRequest), arg0)
}

// DisassociateKmsKeyRequest mocks base method
func (m *MockClientAPI) DisassociateKmsKeyRequest(arg0 *cloudwatchlogs.DisassociateKmsKeyInput) cloudwatchlogs.DisassociateKmsKeyRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisassociateKmsKeyRequest", arg0)
	ret0, _ := ret[0].(cloudwatchlogs.DisassociateKmsKeyRequest)
	return ret0
}

// DisassociateKmsKeyRequest indicates an expected call of DisassociateKmsKeyRequest
func (mr *MockClientAPIMockRecorder) DisassociateKmsKeyRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisassociateKmsKeyRequest", reflect.TypeOf((*MockClientAPI)(nil).DisassociateKmsKeyRequest), arg0)
}

// FilterLogEventsRequest mocks base method
func (m *MockClientAPI) FilterLogEventsRequest(arg0 *cloudwatchlogs.FilterLogEventsInput) cloudwatchlogs.FilterLogEventsRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterLogEventsRequest", arg0)
	ret0, _ := ret[0].(cloudwatchlogs.FilterLogEventsRequest)
	return ret0
}

// FilterLogEventsRequest indicates an expected call of FilterLogEventsRequest
func (mr *MockClientAPIMockRecorder) FilterLogEventsRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterLogEventsRequest", reflect.TypeOf((*MockClientAPI)(nil).FilterLogEventsRequest), arg0)
}

// GetLogEventsRequest mocks base method
func (m *MockClientAPI) GetLogEventsRequest(arg0 *cloudwatchlogs.GetLogEventsInput) cloudwatchlogs.GetLogEventsRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogEventsRequest", arg0)
	ret0, _ := ret[0].(cloudwatchlogs.GetLogEventsRequest)
	return ret0
}

// GetLogEventsRequest indicates an expected call of GetLogEventsRequest
func (mr *MockClientAPIMockRecorder) GetLogEventsRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogEventsRequest", reflect.TypeOf((*MockClientAPI)(nil).GetLogEventsRequest), arg0)
}

// GetLogGroupFieldsRequest mocks base method
func (m *MockClientAPI) GetLogGroupFieldsRequest(arg0 *cloudwatchlogs.GetLogGroupFieldsInput) cloudwatchlogs.GetLogGroupFieldsRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogGroupFieldsRequest", arg0)
	ret0, _ := ret[0].(cloudwatchlogs.GetLogGroupFieldsRequest)
	return ret0
}

// GetLogGroupFieldsRequest indicates an expected call of GetLogGroupFieldsRequest
func (mr *MockClientAPIMockRecorder) GetLogGroupFieldsRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogGroupFieldsRequest", reflect.TypeOf((*MockClientAPI)(nil).GetLogGroupFieldsRequest), arg0)
}

// GetLogRecordRequest mocks base method
func (m *MockClientAPI) GetLogRecordRequest(arg0 *cloudwatchlogs.GetLogRecordInput) cloudwatchlogs.GetLogRecordRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogRecordRequest", arg0)
	ret0, _ := ret[0].(cloudwatchlogs.GetLogRecordRequest)
	return ret0
}

// GetLogRecordRequest indicates an expected call of GetLogRecordRequest
func (mr *MockClientAPIMockRecorder) GetLogRecordRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogRecordRequest", reflect.TypeOf((*MockClientAPI)(nil).GetLogRecordRequest), arg0)
}

// GetQueryResultsRequest mocks base method
func (m *MockClientAPI) GetQueryResultsRequest(arg0 *cloudwatchlogs.GetQueryResultsInput) cloudwatchlogs.GetQueryResultsRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQueryResultsRequest", arg0)
	ret0, _ := ret[0].(cloudwatchlogs.GetQueryResultsRequest)
	return ret0
}

// GetQueryResultsRequest indicates an expected call of GetQueryResultsRequest
func (mr *MockClientAPIMockRecorder) GetQueryResultsRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQueryResultsRequest", reflect.TypeOf((*MockClientAPI)(nil).GetQueryResultsRequest), arg0)
}

// ListTagsLogGroupRequest mocks base method
func (m *MockClientAPI) ListTagsLogGroupRequest(arg0 *cloudwatchlogs.ListTagsLogGroupInput) cloudwatchlogs.ListTagsLogGroupRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTagsLogGroupRequest", arg0)
	ret0, _ := ret[0].(cloudwatchlogs.ListTagsLogGroupRequest)
	return ret0
}

// ListTagsLogGroupRequest indicates an expected call of ListTagsLogGroupRequest
func (mr *MockClientAPIMockRecorder) ListTagsLogGroupRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTagsLogGroupRequest", reflect.TypeOf((*MockClientAPI)(nil).ListTagsLogGroupRequest), arg0)
}

// PutDestinationPolicyRequest mocks base method
func (m *MockClientAPI) PutDestinationPolicyRequest(arg0 *cloudwatchlogs.PutDestinationPolicyInput) cloudwatchlogs.PutDestinationPolicyRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutDestinationPolicyRequest", arg0)
	ret0, _ := ret[0].(cloudwatchlogs.PutDestinationPolicyRequest)
	return ret0
}

// PutDestinationPolicyRequest indicates an expected call of PutDestinationPolicyRequest
func (mr *MockClientAPIMockRecorder) PutDestinationPolicyRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutDestinationPolicyRequest", reflect.TypeOf((*MockClientAPI)(nil).PutDestinationPolicyRequest), arg0)
}

// PutDestinationRequest mocks base method
func (m *MockClientAPI) PutDestinationRequest(arg0 *cloudwatchlogs.PutDestinationInput) cloudwatchlogs.PutDestinationRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutDestinationRequest", arg0)
	ret0, _ := ret[0].(cloudwatchlogs.PutDestinationRequest)
	return ret0
}

// PutDestinationRequest indicates an expected call of PutDestinationRequest
func (mr *MockClientAPIMockRecorder) PutDestinationRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutDestinationRequest", reflect.TypeOf((*MockClientAPI)(nil).PutDestinationRequest), arg0)
}

// PutLogEventsRequest mocks base method
func (m *MockClientAPI) PutLogEventsRequest(arg0 *cloudwatchlogs.PutLogEventsInput) cloudwatchlogs.PutLogEventsRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutLogEventsRequest", arg0)
	ret0, _ := ret[0].(cloudwatchlogs.PutLogEventsRequest)
	return ret0
}

// PutLogEventsRequest indicates an expected call of PutLogEventsRequest
func (mr *MockClientAPIMockRecorder) PutLogEventsRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutLogEventsRequest", reflect.TypeOf((*MockClientAPI)(nil).PutLogEventsRequest), arg0)
}

// PutMetricFilterRequest mocks base method
func (m *MockClientAPI) PutMetricFilterRequest(arg0 *cloudwatchlogs.PutMetricFilterInput) cloudwatchlogs.PutMetricFilterRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutMetricFilterRequest", arg0)
	ret0, _ := ret[0].(cloudwatchlogs.PutMetricFilterRequest)
	return ret0
}

// PutMetricFilterRequest indicates an expected call of PutMetricFilterRequest
func (mr *MockClientAPIMockRecorder) PutMetricFilterRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutMetricFilterRequest", reflect.TypeOf((*MockClientAPI)(nil).PutMetricFilterRequest), arg0)
}

// PutQueryDefinitionRequest mocks base method
func (m *MockClientAPI) PutQueryDefinitionRequest(arg0 *cloudwatchlogs.PutQueryDefinitionInput) cloudwatchlogs.PutQueryDefinitionRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutQueryDefinitionRequest", arg0)
	ret0, _ := ret[0].(cloudwatchlogs.PutQueryDefinitionRequest)
	return ret0
}

// PutQueryDefinitionRequest indicates an expected call of PutQueryDefinitionRequest
func (mr *MockClientAPIMockRecorder) PutQueryDefinitionRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutQueryDefinitionRequest", reflect.TypeOf((*MockClientAPI)(nil).PutQueryDefinitionRequest), arg0)
}

// PutResourcePolicyRequest mocks base method
func (m *MockClientAPI) PutResourcePolicyRequest(arg0 *cloudwatchlogs.PutResourcePolicyInput) cloudwatchlogs.PutResourcePolicyRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutResourcePolicyRequest", arg0)
	ret0, _ := ret[0].(cloudwatchlogs.PutResourcePolicyRequest)
	return ret0
}

// PutResourcePolicyRequest indicates an expected call of PutResourcePolicyRequest
func (mr *MockClientAPIMockRecorder) PutResourcePolicyRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutResourcePolicyRequest", reflect.TypeOf((*MockClientAPI)(nil).PutResourcePolicyRequest), arg0)
}

// PutRetentionPolicyRequest mocks base method
func (m *MockClientAPI) PutRetentionPolicyRequest(arg0 *cloudwatchlogs.PutRetentionPolicyInput) cloudwatchlogs.PutRetentionPolicyRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutRetentionPolicyRequest", arg0)
	ret0, _ := ret[0].(cloudwatchlogs.PutRetentionPolicyRequest)
	return ret0
}

// PutRetentionPolicyRequest indicates an expected call of PutRetentionPolicyRequest
func (mr *MockClientAPIMockRecorder) PutRetentionPolicyRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutRetentionPolicyRequest", reflect.TypeOf((*MockClientAPI)(nil).PutRetentionPolicyRequest), arg0)
}

// PutSubscriptionFilterRequest mocks base method
func (m *MockClientAPI) PutSubscriptionFilterRequest(arg0 *cloudwatchlogs.PutSubscriptionFilterInput) cloudwatchlogs.PutSubscriptionFilterRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutSubscriptionFilterRequest", arg0)
	ret0, _ := ret[0].(cloudwatchlogs.PutSubscriptionFilterRequest)
	return ret0
}

// PutSubscriptionFilterRequest indicates an expected call of PutSubscriptionFilterRequest
func (mr *MockClientAPIMockRecorder) PutSubscriptionFilterRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutSubscriptionFilterRequest", reflect.TypeOf((*MockClientAPI)(nil).PutSubscriptionFilterRequest), arg0)
}

// StartQueryRequest mocks base method
func (m *MockClientAPI) StartQueryRequest(arg0 *cloudwatchlogs.StartQueryInput) cloudwatchlogs.StartQueryRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartQueryRequest", arg0)
	ret0, _ := ret[0].(cloudwatchlogs.StartQueryRequest)
	return ret0
}

// StartQueryRequest indicates an expected call of StartQueryRequest
func (mr *MockClientAPIMockRecorder) StartQueryRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartQueryRequest", reflect.TypeOf((*MockClientAPI)(nil).StartQueryRequest), arg0)
}

// StopQueryRequest mocks base method
func (m *MockClientAPI) StopQueryRequest(arg0 *cloudwatchlogs.StopQueryInput) cloudwatchlogs.StopQueryRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopQueryRequest", arg0)
	ret0, _ := ret[0].(cloudwatchlogs.StopQueryRequest)
	return ret0
}

// StopQueryRequest indicates an expected call of StopQueryRequest
func (mr *MockClientAPIMockRecorder) StopQueryRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopQueryRequest", reflect.TypeOf((*MockClientAPI)(nil).StopQueryRequest), arg0)
}

// TagLogGroupRequest mocks base method
func (m *MockClientAPI) TagLogGroupRequest(arg0 *cloudwatchlogs.TagLogGroupInput) cloudwatchlogs.TagLogGroupRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TagLogGroupRequest", arg0)
	ret0, _ := ret[0].(cloudwatchlogs.TagLogGroupRequest)
	return ret0
}

// TagLogGroupRequest indicates an expected call of TagLogGroupRequest
func (mr *MockClientAPIMockRecorder) TagLogGroupRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TagLogGroupRequest", reflect.TypeOf((*MockClientAPI)(nil).TagLogGroupRequest), arg0)
}

// TestMetricFilterRequest mocks base method
func (m *MockClientAPI) TestMetricFilterRequest(arg0 *cloudwatchlogs.TestMetricFilterInput) cloudwatchlogs.TestMetricFilterRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TestMetricFilterRequest", arg0)
	ret0, _ := ret[0].(cloudwatchlogs.TestMetricFilterRequest)
	return ret0
}

// TestMetricFilterRequest indicates an expected call of TestMetricFilterRequest
func (mr *MockClientAPIMockRecorder) TestMetricFilterRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TestMetricFilterRequest", reflect.TypeOf((*MockClientAPI)(nil).TestMetricFilterRequest), arg0)
}

// UntagLogGroupRequest mocks base method
func (m *MockClientAPI) UntagLogGroupRequest(arg0 *cloudwatchlogs.UntagLogGroupInput) cloudwatchlogs.UntagLogGroupRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UntagLogGroupRequest", arg0)
	ret0, _ := ret[0].(cloudwatchlogs.UntagLogGroupRequest)
	return ret0
}

// UntagLogGroupRequest indicates an expected call of UntagLogGroupRequest
func (mr *MockClientAPIMockRecorder) UntagLogGroupRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UntagLogGroupRequest", reflect.TypeOf((*MockClientAPI)(nil).UntagLogGroupRequest), arg0)
}
