# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
version: 2
before:
  hooks:
    - go mod download
builds:
  - id: "cli-amd64"
    env:
      - CGO_ENABLED=0
    main: ./cmd/cloudwatch-logs-agent-lite/main.go
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    binary: cloudwatch-logs-agent-lite
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
  - id: "cli-arm64"
    env:
      - CGO_ENABLED=0
    main: ./cmd/cloudwatch-logs-agent-lite/main.go
    goos:
      - linux
      - darwin
    goarch:
      - arm64
    binary: cloudwatch-logs-agent-lite
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
archives:
  - ids:
      - cli-amd64
      - cli-arm64
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ .Tag }}-next"

# https://songmu.jp/riji/entry/2025-09-05-coordinate-tagpr-and-goreleaser-with-immutable-releases.html
release:
  use_existing_draft: true

changelog:
  use: github-native

nfpms:
  - id: package-amd64
    ids:
      - cli-amd64
    homepage: https://github.com/shogo82148/cloudwatch-logs-agent-lite/
    maintainer: ICHINOSE Shogo <shogo82148@gmail.com>
    description: Lightweight log forwarder with CloudWatch
    license: MIT
    formats:
      - apk
      - deb
      - rpm
    release: 1
    epoch: 0
    bindir: /usr/bin
  - id: package-arm64
    ids:
      - cli-arm64
    homepage: https://github.com/shogo82148/cloudwatch-logs-agent-lite/
    maintainer: ICHINOSE Shogo <shogo82148@gmail.com>
    description: Lightweight log forwarder with CloudWatch
    license: MIT
    formats:
      - apk
      - deb
      - rpm
    release: 1
    epoch: 0
    bindir: /usr/bin

blobs:
  - provider: s3
    bucket: shogo82148-rpm-temporary
    ids: [package-amd64]
    directory: amazonlinux/2/x86_64/cloudwatch-logs-agent-lite
  - provider: s3
    bucket: shogo82148-rpm-temporary
    ids: [package-arm64]
    directory: amazonlinux/2/aarch64/cloudwatch-logs-agent-lite
  - provider: s3
    bucket: shogo82148-rpm-temporary
    ids: [package-amd64]
    directory: amazonlinux/2023/x86_64/cloudwatch-logs-agent-lite
  - provider: s3
    bucket: shogo82148-rpm-temporary
    ids: [package-arm64]
    directory: amazonlinux/2023/aarch64/cloudwatch-logs-agent-lite
  - provider: s3
    bucket: shogo82148-rpm-temporary
    ids: [package-amd64]
    directory: centos/7/x86_64/cloudwatch-logs-agent-lite
  - provider: s3
    bucket: shogo82148-rpm-temporary
    ids: [package-arm64]
    directory: centos/7/aarch64/cloudwatch-logs-agent-lite
  - provider: s3
    bucket: shogo82148-rpm-temporary
    ids: [package-amd64]
    directory: almalinux/8/x86_64/cloudwatch-logs-agent-lite
  - provider: s3
    bucket: shogo82148-rpm-temporary
    ids: [package-arm64]
    directory: almalinux/8/aarch64/cloudwatch-logs-agent-lite
  - provider: s3
    bucket: shogo82148-rpm-temporary
    ids: [package-amd64]
    directory: almalinux/9/x86_64/cloudwatch-logs-agent-lite
  - provider: s3
    bucket: shogo82148-rpm-temporary
    ids: [package-arm64]
    directory: almalinux/9/aarch64/cloudwatch-logs-agent-lite
  - provider: s3
    bucket: shogo82148-rpm-temporary
    ids: [package-amd64]
    directory: rockylinux/8/x86_64/cloudwatch-logs-agent-lite
  - provider: s3
    bucket: shogo82148-rpm-temporary
    ids: [package-arm64]
    directory: rockylinux/8/aarch64/cloudwatch-logs-agent-lite
  - provider: s3
    bucket: shogo82148-rpm-temporary
    ids: [package-amd64]
    directory: rockylinux/9/x86_64/cloudwatch-logs-agent-lite
  - provider: s3
    bucket: shogo82148-rpm-temporary
    ids: [package-arm64]
    directory: rockylinux/9/aarch64/cloudwatch-logs-agent-lite
