name: goreleaser

on:
  push:
    tags:
      - "v*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Configure AWS Credentials
        uses: shogo82148/actions-aws-assume-role@v1
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::445285296882:role/rpm-repository-users-CloudWatchLogsAgentRole-19MYK77MOJY8B
          role-session-tagging: true

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: "~> v2"
          args: release --cleanup
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
